### ISSUE TITLE
incorrect transformation examples?

### ISSUE THREAD

**Issue by gcentauri** [opensolid/svg#1]
Hi, I was just trying out your svg module and was having trouble drawing the rotated circles.  It seemed like the line
`
in
        Svg.g []
            (centerPoint2d referencePoint
                :: List.map rotatedCircle angles
            )
`
is referencing this centerPoint2d function that is never given.  I looked at your example source code and found the function, so got it working, but the page on the Elm packages site seems to be missing this.  I may have just missed it myself, but I thought I'd let you know just in case!

**Comment by ianmackenzie** [comment]
Thanks for the report! I'll have to figure out a different way to do the examples - I didn't want to include the helper functions like `centerPoint2d` and `axis2d` in the actual package since they seemed too specialized and arbitrary to include in a general-purpose SVG library, but it is a bit weird that having them in the examples means you can't just copy-paste the examples and try them out.

**Comment by ianmackenzie** [comment]
Just published `opensolid/svg` 1.0.2 which has more self-contained documentation examples (and now depends on `opensolid/geometry` 1.1.0, since I added a `LineSegment2d.along` function there to make drawing axes a bit easier). Let me know if you run into anything else!
